name: 'Check PR Approvers'
description: 'Verifica se o pull request possui o número mínimo de aprovações de membros dos times definidos no CODEOWNERS'
author: 'DevSecOps Squad'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github-token:
    description: 'GitHub token para acessar a API'
    required: true
  organization:
    description: 'Nome da organização do repositório'
    required: true
  repository:
    description: 'Nome do repositório'
    required: true
  pull-request-number:
    description: 'Número do pull request'
    required: true
  codeowners-path:
    description: 'Caminho para o arquivo CODEOWNERS'
    required: false
    default: '.github/CODEOWNERS'
  required-approvals-main:
    description: 'Número mínimo de aprovações para branch main (fallback)'
    required: false
    default: '2'
  required-approvals-develop:
    description: 'Número mínimo de aprovações para branches develop/hotfix (fallback)'
    required: false
    default: '1'
  required-approvals-feature:
    description: 'Número mínimo de aprovações para feature branches (fallback)'
    required: false
    default: '1'
  skip-branch-patterns:
    description: 'Padrões de branches que devem ser ignorados (separados por vírgula)'
    required: false
    default: ''

outputs:
  approved-count:
    description: 'Número de aprovações válidas encontradas'
  required-count:
    description: 'Número mínimo de aprovações necessárias'
  status:
    description: 'Status da verificação (success, failed)'

runs:
  using: 'composite'
  steps:
    - name: 'Verificar Aprovadores do PR'
      run: ${{ github.action_path }}/scripts/check-approvers.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_ORGANIZATION: ${{ inputs.organization }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
        INPUT_CODEOWNERS_PATH: ${{ inputs.codeowners-path }}
        INPUT_REQUIRED_APPROVALS_MAIN: ${{ inputs.required-approvals-main }}
        INPUT_REQUIRED_APPROVALS_DEVELOP: ${{ inputs.required-approvals-develop }}
        INPUT_REQUIRED_APPROVALS_FEATURE: ${{ inputs.required-approvals-feature }}
        INPUT_SKIP_BRANCH_PATTERNS: ${{ inputs.skip-branch-patterns }}
